query {
  repositoryOwner(login: "hiveminds") {
    repositories(first: 3, after: "Y3Vyc29yOnYyOpHODH7CdA==") {
      edges {
        node {
          nameWithOwner
          ... on Repository {
            defaultBranchRef {
              target {
                ... on Commit {
                  history(first: 10) {
                    edges {
                      node {
                        ... on Commit {
                          committedDate
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
        cursor
      }
    }
  }
}
