query {repositoryOwner(login:"danbst") {
    repositories(first: 2) {
      edges {
        node {
          nameWithOwner
          pullRequests(last: 3, states: OPEN) {
            edges {
              node {
                title
                url
                author {
                  login
                }
                labels(first: 2) {
                  edges {
                    node {
                      name
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}