#!/bin/bash
read oldrev newrev refname

path_to_gitlab_post_receive_dir="/opt/gitlab/embedded/service/gitlab-shell/hooks/post-receive.d"
#path_to_gitlab_post_receive_dir="src"
"$path_to_gitlab_post_receive_dir"/./post-receive_backup "$oldrev" "$newrev" "$refname"
echo "Started post-receive script" > "direct_post_receive_log.txt"
for i in {1..120}
do
	echo "Welcome $i times" >> "direct_post_receive_log.txt"
	sleep 2
done
